fullnameOverride: chartmuseum

replica:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    iam.amazonaws.com/role: "eks-demo-worker-bucket"

env:
  open:
    DEBUG: false
    DISABLE_API: false
    DISABLE_METRICS: false
    ALLOW_OVERWRITE: true

    STORAGE: "amazon"
    STORAGE_AMAZON_BUCKET: "eks-demo-chartmuseum-demo"
    STORAGE_AMAZON_PREFIX: "/"
    STORAGE_AMAZON_REGION: "ap-northeast-2"
  # secret:
  #   BASIC_AUTH_USER: "server"
  #   BASIC_AUTH_PASS: "924426A5-DA22-4A10-9FB1-418761684372"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
  hosts:
    - name: "chartmuseum.closed.mzdev.be"
      path: /
      tls: true
      tlsSecret: chartmuseum-tls
